### ISSUE TITLE
The users with @ in their names, are not properly handled in all cases

### ISSUE THREAD

**Issue by MahdiBaghbani** [sciencemesh/nc-sciencemesh#48]
This is the continuation of this one https://github.com/pondersource/nc-sciencemesh/issues/272

I didn't know at the time that we were using string splitting based on @ in many places! so that all have to be changed to handle multiple @ in a `username@idp`.

Right now cases like `thirsa@dev@surf.nl` will cause problems.

**Comment by glpatcern** [comment]
Fixed in 0.6
