### ISSUE TITLE
Last modification time may be equal to Unix Epoch

### ISSUE THREAD

**Issue by glpatcern** [sciencemesh/nc-sciencemesh#50]
A newly created file/folder may appear as having been created at Unix Epoch time. A subsequent modification makes the modif time correct.

Likely because of https://github.com/sciencemesh/nc-sciencemesh/blob/99e1cd88489a35e48c4032d4ee3fc4c70715bf93/lib/Controller/RevaController.php#L250

**Comment by MahdiBaghbani** [comment]
Yes, it's definitely because of that.

**Comment by MahdiBaghbani** [comment]
Need testing to see if it shows the correct time for modifying.

**Comment by glpatcern** [comment]
Confirmed this works
