### ISSUE TITLE
Compatibility with the federated groups share app

### ISSUE THREAD

**Issue by MahdiBaghbani** [sciencemesh/nc-sciencemesh#62]
Steps to follow:
1. clone dev-stock `enhancment` branch (preferred way is GitPod)
2. run ./docker/delete-all-images.sh
3. run ./docker/build/all.sh
4. run ./init/sm-sram-ocm.sh
5. run ./tests/sm-sram-ocm.sh
6. open the exposed firefox port on localhost (or GitPod)

Sciencemesh shares are ok. see below:

![smfgocm-sm](https://github.com/sciencemesh/nc-sciencemesh/assets/13681688/fbfa4ee3-4f83-4969-b5d1-2e64b69bfe54)

![smfgocm-sm-2](https://github.com/sciencemesh/nc-sciencemesh/assets/13681688/dabab52d-da4f-4b88-a292-767eba04b28f)

share to the group currently fails with:

![smfgocm-fg](https://github.com/sciencemesh/nc-sciencemesh/assets/13681688/6e2f1b6a-9309-4480-94dd-070f663a8a0b)

```json
{
  "reqId": "MMAKG1prCHaSTWR1sXUk",
  "level": 3,
  "time": "2023-10-18T18:56:04+00:00",
  "remoteAddr": "172.19.0.3",
  "user": "einstein",
  "app": "PHP",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json",
  "message": "Undefined index: statusCode at /var/www/html/apps/opencloudmesh/lib/FederatedFileSharing/AbstractNotifications.php#439"
}
```

```json
{
  "reqId": "MMAKG1prCHaSTWR1sXUk",
  "level": 3,
  "time": "2023-10-18T18:56:04+00:00",
  "remoteAddr": "172.19.0.3",
  "user": "einstein",
  "app": "no app in context",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json",
  "message": "Failed to notify remote server of mixed group share, panic (Sharing ShareGroups failed, could not find TestGroup (uniharderwijk_surfdrive_test) (SRAM CO), maybe the server is currently unreachable.)"
}
```

I don't know if it is related to the compatibility scripts or if something on the rd-SRAM is the problem, I need help here.

**Comment by glpatcern** [comment]
Fixed in 0.6
